zuul:
  ignoredServices: '*'
  prefix: /api/v1
  routes:
    admin-users:
      path: /admin/user/**
      serviceId: admin-service
      strip-prefix: false
    admin-types:
      path: /admin/type/**
      serviceId: admin-service
      strip-prefix: false
    admin-statistics:
      path: /admin/product/statictics/**
      serviceId: admin-service
      strip-prefix: false
    admin-saleoffs:
      path: /admin/sale/**
      serviceId: admin-service
      strip-prefix: false
    admin-product:
      path: /admin/product/**
      serviceId: admin-service
      strip-prefix: false
    user-user:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
    guest-guest:
      path: /guest/**
      serviceId: guest-service
      strip-prefix: false

eureka :
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost